const isCreate=location.pathname.endsWith('create.html');const isOrder=location.pathname.endsWith('order.html');
const defaults={forWhom:'',name:'',occasion:'',genre:'',voice:'',language:'Spanish',qualities:'',memory:'',exactPhrase:'',emotion:'',email:'',phone:''};
let data={...defaults,...JSON.parse(localStorage.getItem('sonalzaOrder')||'{}')};let step=Number(localStorage.getItem('sonalzaStep')||1);
const qs=(s)=>document.querySelector(s),qsa=(s)=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('sonalzaOrder',JSON.stringify(data));localStorage.setItem('sonalzaStep',String(step))}
const opts=(key,arr)=>`<div class="options">${arr.map(v=>`<button type="button" class="option ${data[key]===v?'active':''}" data-key="${key}" data-value="${v}">${v}</button>`).join('')}</div>`;
function render(){if(!isCreate)return;const q=qs('#question');const content={
1:`<h1>Who’s this song for?</h1><p class="sub">Pick the closest relationship.</p>${opts('forWhom',['Husband','Wife','Partner','Boyfriend','Girlfriend','Father','Mother','Son','Daughter','Grandparent','Friend','Myself','Business','Other'])}`,
2:`<h1>What’s their name?</h1><p class="sub">Use the name you want us to sing.</p><div class="field-wrap"><input class="field" id="name" maxlength="50" placeholder="First name or nickname" value="${esc(data.name)}"></div>`,
3:`<h1>What’s the occasion?</h1><p class="sub">Why are you making this song?</p>${opts('occasion',['Just Because','I Love You','Birthday','Anniversary','Wedding','Thank You','Graduation','Retirement','In Memory','Milestone','Apology','Proposal','Business','Something else'])}`,
4:`<h1>Choose the sound.</h1><p class="sub">This is where SONALZA gets specific.</p>${opts('genre',['Corrido','Banda','Norteño','Mariachi','Cumbia','Duranguense','Huapango','Reggaetón','Balada','Pop Latino','Sierreño','Surprise Me'])}<div style="height:20px"></div><p><strong>Voice</strong></p>${opts('voice',['Male','Female','Surprise Me'])}<div style="height:18px"></div><p><strong>Language</strong></p>${opts('language',['Spanish','English','Bilingual'])}`,
5:`<h1>What makes them special?</h1><p class="sub">Give us the qualities that make this person who they are.</p><div class="field-wrap"><textarea class="textarea" id="qualities" placeholder="Patient, funny, strong, protective, hardworking...">${esc(data.qualities)}</textarea><div class="helper">Aim for 1–3 sentences. Specific beats generic.</div></div>`,
6:`<h1>Share a memory we can use.</h1><p class="sub">A real moment makes the song feel unmistakably theirs.</p><div class="field-wrap"><textarea class="textarea" id="memory" placeholder="How you met, a family moment, a hard season you survived, an inside joke...">${esc(data.memory)}</textarea></div>`,
7:`<h1>What must the song say or make them feel?</h1><p class="sub">This is the emotional target.</p><div class="field-wrap"><input class="field" id="exactPhrase" placeholder="Exact phrase to include (optional)" value="${esc(data.exactPhrase)}"><div style="height:14px"></div><textarea class="textarea" id="emotion" placeholder="What do you want them to know, feel or remember?">${esc(data.emotion)}</textarea></div>`,
8:`<h1>Where should we send it?</h1><p class="sub">We’ll use this for order delivery and updates.</p><div class="field-wrap"><input class="field" id="email" type="email" placeholder="you@email.com" value="${esc(data.email)}"><div style="height:14px"></div><input class="field" id="phone" placeholder="Phone number (optional)" value="${esc(data.phone)}"></div>`};q.innerHTML=content[step];qs('#stepLabel').textContent=`Step ${step} of 8`;qs('#pctLabel').textContent=`${Math.round(step/8*100)}% Complete`;qs('#bar').style.width=`${step/8*100}%`;qs('#backBtn').style.visibility=step===1?'hidden':'visible';qs('#nextBtn').textContent=step===8?'Review Order →':'Next →';bindDynamic()}
function bindDynamic(){qsa('.option').forEach(b=>b.onclick=()=>{data[b.dataset.key]=b.dataset.value;save();render()});[['name','name'],['qualities','qualities'],['memory','memory'],['exactPhrase','exactPhrase'],['emotion','emotion'],['email','email'],['phone','phone']].forEach(([id,key])=>{const el=qs('#'+id);if(el)el.oninput=()=>{data[key]=el.value;save()}})}
function valid(){if(step===1)return !!data.forWhom;if(step===2)return data.name.trim().length>0;if(step===3)return !!data.occasion;if(step===4)return !!data.genre&&!!data.voice&&!!data.language;if(step===5)return data.qualities.trim().length>=5;if(step===6)return data.memory.trim().length>=5;if(step===7)return data.emotion.trim().length>=5;if(step===8)return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email);return true}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
if(isCreate){render();qs('#nextBtn').onclick=()=>{if(!valid()){alert('Please complete this step before continuing.');return}if(step<8){step++;save();render();scrollTo({top:0,behavior:'smooth'})}else{save();location.href='order.html'}};qs('#backBtn').onclick=()=>{if(step>1){step--;save();render()}}}
if(isOrder){const labels=[['For',`${data.name||'—'} (${data.forWhom||'—'})`],['Occasion',data.occasion||'—'],['Music style',data.genre||'—'],['Voice',data.voice||'—'],['Language',data.language||'—'],['Email',data.email||'—']];qs('#briefRows').innerHTML=labels.map(([a,b])=>`<div class="summary-row"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('');function calc(){let t=59;qsa('.addon:checked').forEach(x=>t+=Number(x.dataset.price));qs('#total').textContent='$'+t;localStorage.setItem('sonalzaTotal',String(t))}qsa('.addon').forEach(x=>x.onchange=calc);calc();qs('#checkoutBtn').onclick=()=>alert('Checkout is not connected in this prototype yet. The next step is wiring the payment processor and order automation.')}
function setupExit(){const modal=qs('#exitModal');if(!modal)return;let shown=false;function show(){if(shown)return;shown=true;modal.classList.add('show')}document.addEventListener('mouseout',e=>{if(e.clientY<=0)show()});window.addEventListener('popstate',show);qs('#closeModal').onclick=()=>modal.classList.remove('show');qsa('.reason').forEach(b=>b.onclick=()=>{localStorage.setItem('sonalzaExitReason',b.dataset.reason);modal.innerHTML='<div class="modal-card"><h2>Thank you.</h2><p>That feedback was saved in this browser for the prototype.</p><button class="btn btn-primary" onclick="document.getElementById(\'exitModal\').classList.remove(\'show\')">Continue</button></div>'})}setupExit();
