-- SONALZA STUDIOS - Supabase production schema
-- V31: order lifecycle, private files, payment audit trail, and idempotency.
-- Safe to run more than once.

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  submitted_at timestamptz,
  paid_at timestamptz,
  status text not null default 'pending_payment',
  payment_status text not null default 'unpaid',
  fulfillment_status text not null default 'not_started',
  product text not null,
  region text not null default 'US',
  language text not null default 'en',
  currency text not null,
  total numeric not null,
  addons jsonb not null default '[]'::jsonb,
  customer_name text,
  customer_email text not null,
  customer_phone text,
  brief jsonb not null,
  source jsonb not null default '{}'::jsonb,
  client_request_id text unique,
  coupon_code text,
  coupon_discount numeric not null default 0,
  detected_country text,
  region_override boolean not null default false,
  region_verification_required boolean not null default false,
  terms_accepted boolean not null default false,
  privacy_accepted boolean not null default false,
  materials_accepted boolean not null default false,
  terms_version text,
  privacy_version text,
  accepted_at timestamptz,
  acceptance_evidence jsonb not null default '{}'::jsonb,
  payment_provider text,
  stripe_session_id text unique,
  stripe_payment_intent_id text,
  stripe_customer_id text,
  cover_bucket text,
  cover_path text,
  cover_uploaded_at timestamptz,
  admin_notified_at timestamptz,
  customer_paid_email_at timestamptz
);

-- Migration-safe additions for databases created by earlier SONALZA versions.
alter table public.orders add column if not exists updated_at timestamptz not null default now();
alter table public.orders add column if not exists submitted_at timestamptz;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists payment_status text not null default 'unpaid';
alter table public.orders add column if not exists fulfillment_status text not null default 'not_started';
alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists client_request_id text;
alter table public.orders add column if not exists region text not null default 'US';
alter table public.orders add column if not exists language text not null default 'en';
alter table public.orders add column if not exists coupon_code text;
alter table public.orders add column if not exists coupon_discount numeric not null default 0;
alter table public.orders add column if not exists detected_country text;
alter table public.orders add column if not exists region_override boolean not null default false;
alter table public.orders add column if not exists region_verification_required boolean not null default false;
alter table public.orders add column if not exists terms_accepted boolean not null default false;
alter table public.orders add column if not exists privacy_accepted boolean not null default false;
alter table public.orders add column if not exists materials_accepted boolean not null default false;
alter table public.orders add column if not exists terms_version text;
alter table public.orders add column if not exists privacy_version text;
alter table public.orders add column if not exists accepted_at timestamptz;
alter table public.orders add column if not exists acceptance_evidence jsonb not null default '{}'::jsonb;
alter table public.orders add column if not exists payment_provider text;
alter table public.orders add column if not exists stripe_session_id text;
alter table public.orders add column if not exists stripe_payment_intent_id text;
alter table public.orders add column if not exists stripe_customer_id text;
alter table public.orders add column if not exists cover_bucket text;
alter table public.orders add column if not exists cover_path text;
alter table public.orders add column if not exists cover_uploaded_at timestamptz;
alter table public.orders add column if not exists admin_notified_at timestamptz;
alter table public.orders add column if not exists customer_paid_email_at timestamptz;

create unique index if not exists orders_client_request_id_uidx on public.orders (client_request_id) where client_request_id is not null;
create unique index if not exists orders_stripe_session_id_uidx on public.orders (stripe_session_id) where stripe_session_id is not null;
create index if not exists orders_status_created_idx on public.orders (status, created_at desc);
create index if not exists orders_email_created_idx on public.orders (customer_email, created_at desc);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(order_id) on delete cascade,
  created_at timestamptz not null default now(),
  event_type text not null,
  actor text not null default 'system',
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists order_events_order_created_idx on public.order_events (order_id, created_at desc);

create table if not exists public.order_files (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(order_id) on delete cascade,
  created_at timestamptz not null default now(),
  kind text not null,
  bucket text not null,
  path text not null,
  mime_type text,
  byte_size bigint,
  original_name text,
  metadata jsonb not null default '{}'::jsonb,
  unique(bucket, path)
);
create index if not exists order_files_order_idx on public.order_files (order_id, created_at desc);

create table if not exists public.stripe_events (
  stripe_event_id text primary key,
  event_type text not null,
  created_at timestamptz not null default now(),
  stripe_created_at timestamptz,
  livemode boolean,
  object_id text,
  order_id text,
  processed boolean not null default false,
  processing_error text
);
create index if not exists stripe_events_order_idx on public.stripe_events (order_id, created_at desc);

create table if not exists public.business_leads (
  id bigint generated by default as identity primary key,
  lead_id text unique not null,
  created_at timestamptz not null default now(),
  status text not null default 'new',
  name text,
  business text,
  email text not null,
  phone text,
  project_type text,
  budget text,
  message text,
  currency text,
  region text not null default 'US',
  language text not null default 'en',
  detected_country text,
  region_override boolean not null default false,
  region_verification_required boolean not null default false,
  privacy_consent boolean not null default false,
  privacy_version text,
  acceptance_evidence jsonb not null default '{}'::jsonb
);
alter table public.business_leads add column if not exists region text not null default 'US';
alter table public.business_leads add column if not exists language text not null default 'en';
alter table public.business_leads add column if not exists detected_country text;
alter table public.business_leads add column if not exists region_override boolean not null default false;
alter table public.business_leads add column if not exists region_verification_required boolean not null default false;
alter table public.business_leads add column if not exists privacy_consent boolean not null default false;
alter table public.business_leads add column if not exists privacy_version text;
alter table public.business_leads add column if not exists acceptance_evidence jsonb not null default '{}'::jsonb;

create table if not exists public.exit_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  reason text,
  page text,
  currency text,
  region text,
  language text
);
alter table public.exit_feedback add column if not exists region text;
alter table public.exit_feedback add column if not exists language text;

-- Private bucket for customer-supplied cover reference photos.
insert into storage.buckets (id, name, public)
values ('sonalza-covers', 'sonalza-covers', false)
on conflict (id) do update set public = false;

-- Service-role-only architecture: no public storage policies are created.
-- The browser never receives the Supabase service-role key.

alter table public.orders enable row level security;
alter table public.order_events enable row level security;
alter table public.order_files enable row level security;
alter table public.stripe_events enable row level security;
alter table public.business_leads enable row level security;
alter table public.exit_feedback enable row level security;

create or replace function public.sonalza_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.sonalza_set_updated_at();
