create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  created_at timestamptz not null default now(),
  status text not null default 'pending_payment',
  product text not null,
  currency text not null,
  total numeric not null,
  addons jsonb not null default '[]'::jsonb,
  customer_email text not null,
  customer_phone text,
  brief jsonb not null,
  source jsonb not null default '{}'::jsonb
);

create table if not exists public.business_leads (
  id bigint generated by default as identity primary key,
  lead_id text unique not null,
  created_at timestamptz not null default now(),
  status text not null default 'new',
  name text,
  business text,
  email text not null,
  phone text,
  project_type text,
  budget text,
  message text,
  currency text
);

create table if not exists public.exit_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  reason text,
  page text,
  currency text
);

alter table public.orders enable row level security;
alter table public.business_leads enable row level security;
alter table public.exit_feedback enable row level security;
