create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  created_at timestamptz not null default now(),
  status text not null default 'pending_payment',
  product text not null,
  region text not null default 'US',
  language text not null default 'en',
  currency text not null,
  total numeric not null,
  addons jsonb not null default '[]'::jsonb,
  customer_email text not null,
  customer_phone text,
  brief jsonb not null,
  source jsonb not null default '{}'::jsonb
);

create table if not exists public.business_leads (
  id bigint generated by default as identity primary key,
  lead_id text unique not null,
  created_at timestamptz not null default now(),
  status text not null default 'new',
  name text,
  business text,
  email text not null,
  phone text,
  project_type text,
  budget text,
  message text,
  currency text,
  region text not null default 'US',
  language text not null default 'en'
);

create table if not exists public.exit_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  reason text,
  page text,
  currency text,
  region text,
  language text
);

alter table public.orders enable row level security;
alter table public.business_leads enable row level security;
alter table public.exit_feedback enable row level security;

-- If upgrading an existing database, run these once:
alter table public.orders add column if not exists region text not null default 'US';
alter table public.orders add column if not exists language text not null default 'en';

alter table public.business_leads add column if not exists region text not null default 'US';
alter table public.business_leads add column if not exists language text not null default 'en';

alter table public.exit_feedback add column if not exists region text;
alter table public.exit_feedback add column if not exists language text;

-- V13 · regional pricing verification metadata
alter table public.orders add column if not exists detected_country text;
alter table public.orders add column if not exists region_override boolean not null default false;
alter table public.orders add column if not exists region_verification_required boolean not null default false;

alter table public.business_leads add column if not exists detected_country text;
alter table public.business_leads add column if not exists region_override boolean not null default false;
alter table public.business_leads add column if not exists region_verification_required boolean not null default false;
